name: Push Docker Images to Google Artifact Registry

on:
  push:
    branches:
      - main  # or any branch you want to trigger this workflow
      - consistent-jupyter-setup #TODO REMOVE

jobs:
  push-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        version: 'latest'
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Google Artifact Registry
      run: gcloud auth configure-docker

    - name: Run script to push Docker images
      run: |
        chmod +x scripts/push_docker_images.sh
        ./scripts/push_docker_images.sh .
